# Generated by Django 4.1.1 on 2022-09-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='receiver',
            new_name='receipient',
        ),
    ]
