# Generated by Django 4.1.1 on 2022-09-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_rename_receiver_conversation_receipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[(0, 'delivered'), (1, 'awaiting')], max_length=100, null=True),
        ),
    ]
