# Generated by Django 4.1.1 on 2022-09-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_message_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Conversation_id',
            new_name='conversation_id',
        ),
    ]
